name: 'Lighthouse CI'
on:
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://moose-dev.d1.moderntribe.qa/?secret=1
          # budgetPath: .github/lighthouse/budget.json
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: false # upload lighthouse report to the temporary storage
          configPath: .github/lighthouse/lighthouserc.json
